version: '3.8'

services:
  browserless:
    image: ghcr.io/browserless/chromium
    container_name: browserless
    ports:
      - "3000:3000"
    environment:
      - TOKEN=meu_token_seguro
      - PRE_REQUEST_HEALTH_CHECK=true
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=5
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_LAUNCH_ARGS=["--no-sandbox"]
    restart: unless-stopped
